nama: Test User

spring:
    datasource:
        driverClassName: 'org.postgresql.Driver'
        url: 'jdbc:postgresql://localhost:5432/ecomerce'
        username: 'postgres'
        password: 'rioters7'
